/**
 ******************************************************************************
 * Xenia : Xbox 360 Emulator Research Project                                 *
 ******************************************************************************
 * Kinect (NUI) HLE: masked word signatures for statically linked SDK code.
 * Tables are generated by tools/nui/gen_signatures.py, one per SDK version.
 ******************************************************************************
 */

#ifndef XENIA_KERNEL_NUI_NUI_SIGNATURE_H_
#define XENIA_KERNEL_NUI_NUI_SIGNATURE_H_

#include <cstdint>

namespace xe {
namespace kernel {
namespace nui {

// One masked instruction word.
struct NuiSigWord {
  uint32_t value;  // already masked
  uint32_t mask;
};
struct NuiSdkSignature {
  const char* name;
  const NuiSigWord* words;
  uint32_t word_count;
  // XREF anchor: word index of a `b`/`bl` whose target must match `target`
  // (-1: none). Used where the body alone is a thunk shared by many entries.
  int32_t follow_index;
  const NuiSigWord* target;
  uint32_t target_count;
  const char* target_name;
};

// Scans [text, text + size) (guest big-endian words, base guest address
// `text_address`) for `sig`. Returns the number of matches; the first is
// stored in *address. Exposed for tests.
uint32_t FindSignature(const uint8_t* text, uint32_t text_address,
                       uint32_t size, const NuiSdkSignature& sig,
                       uint32_t* address);

}  // namespace nui
}  // namespace kernel
}  // namespace xe

#endif  // XENIA_KERNEL_NUI_NUI_SIGNATURE_H_
