#!/bin/bash
# run_dc3_oracle.sh -- boot the ORIGINAL DC3 debug.xex under this worktree's
# xenia-headless with a PRIVATE storage root and a PINNED config file.
#
# Never touches ~/.local/share/Xenia: --storage_root points at a private dir and
# --config at the pinned, all-defaults toml checked in next to this script
# (generated by this binary with an empty storage root). Every cvar that
# differs from the compiled-in default is passed on the command line below.
#
# usage: run_dc3_oracle.sh <run-dir> [gpu: null|vulkan] [timeout_s] [extra cvars...]
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
WT="$(cd "$HERE/../.." && pwd)"
DC3="${DC3:-/home/free/code/milohax/dc3-decomp}"
XENIA="${XENIA:-$WT/build/bin/Linux/Checked/xenia-headless}"
RUN="${1:?run dir}"; GPU="${2:-null}"; TIMEOUT_S="${3:-240}"; shift 3 || shift $#
mkdir -p "$RUN/storage" "$RUN/frames"
cvars=(
  --storage_root="$RUN/storage"
  --config="$HERE/xenia.dc3-oracle.defaults.toml"
  --target="$DC3/orig/373307D9/debug.xex"
  --gpu="$GPU"
  --vulkan_device="${VULKAN_DEVICE:-1}"
  --dc3_nui_patch_layout=original
  --dc3_crt_skip_nui=true
  --stub_nui_functions=true
  --fake_kinect_data=true
  --scripted_input_file="$DC3/scripts/dc3-input-flows/xenia-ymca.txt"
  --headless_timeout_ms=$(( (TIMEOUT_S - 10) * 1000 ))
)
if [ "$GPU" = vulkan ]; then
  cvars+=( --dump_frames_path="$RUN/frames" --headless_capture_interval=300 )
fi
cvars+=( "$@" )
{
  echo "# xenia: $XENIA"
  echo "# xxh3:  $(xxhsum -H3 "$XENIA" | awk '{print $1}')"
  echo "# xex sha256: $(sha256sum "$DC3/orig/373307D9/debug.xex" | awk '{print $1}')"
  echo "# git: $(git -C "$WT" rev-parse HEAD) $(git -C "$WT" status --porcelain --ignore-submodules=all | wc -l) dirty"
  printf '# cmd: %q' "$XENIA"; printf ' %q' "${cvars[@]}"; echo
} > "$RUN/cmd.txt"
cd "$RUN"
start=$(date +%s.%N)
set +e
timeout -k 10 "$TIMEOUT_S" "$XENIA" "${cvars[@]}" > "$RUN/run.log" 2>&1
rc=$?
set -e
end=$(date +%s.%N)
echo "# rc=$rc wall=$(echo "$end - $start" | bc)s" >> "$RUN/cmd.txt"
cat "$RUN/cmd.txt"
